<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Feliz Aniversario</title>
        <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400italic' rel='stylesheet' type='text/css'>
	</head>
	<body>
            <div style="width: 480px; height: 300px; top: 0px; left: 0px; position: relative; z-index: -1;">
                    <img src="{img_path}" alt="Tarjeta de Aniversario"/>
		</div>
                <table style="color:white; font-family: 'Droid Serif', serif; border-collapse: collapse; position: absolute; left: 45px; top: 91px; text-align: center; z-index: 2; width: 380px; height: 160px; color: white;">
                        <thead></thead>
                        <tbody>
                            
