</table>
</td>
</tr>
</table>
</td>
</tr>

<!--********************************************************
                                        FIN - Tabla de Body
************************************************************-->

<tr style="width:90%;">
    <td style="width:100%">
        <!--********************************************************
                                                Tabla de Footer
        ************************************************************-->
        <table cellpadding="0" cellspacing="0" style="width:100%; margin:0 auto; background-color: #890300;">
            <tr style="width:100%">
                <!--td style="width:100%; color: #FFF; font-size: 0.688em; text-align: center">
                    <p style="width:100%; margin-bottom:2px;">
                        </br>
                        </br>
                        <em>Desarrollado por la Unidad de Aplicaciones y Desarrollo.</em>
                    </p>
                    <p style="width:100%; margin-top:2px;">La nueva Televisión del Sur C.A. (TVSUR)</p>
                </td-->
                <td style="max-width:100%; min-width:320px;">
                    <img style="width:100%; min-width:320px;" src="http://localhost/Tarjeta-General-inferior.jpg" longdesc="http://localhost/Tarjeta-General-inferior.jpg" />
                </td>
            </tr>
        </table>
        <!--********************************************************
                                                FIN - Tabla de Footer
        ************************************************************-->
    </td>
</tr>
</table>
</body>
</html>