<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Feliz Aniversario</title>
    </head>
    <body style="padding: 0; margin: 0 auto !important; min-width: 320px !important;">
        <table style="max-width:600px; min-width: 320px !important; margin: 0 auto !important; background: #EAEAEA;">
            <tr style="width:90%;">
                <td style="width:100%">
                    <!--********************************************************
                                                                Tabla de Header
                    ************************************************************-->
                    <table style="width:100%; margin:0 auto; background-color: #8C0603;">
                        <tr style="width:100%">
                            <td style="max-width:100%; min-width:320px;">
                                <img style="width:100%; min-width:320px;" src="http://localhost/Tarjeta-General-superior.jpg" longdesc="http://localhost/Tarjeta-General-superior.jpg" />
                            </td>
                        </tr>
                    </table>
                    <!--********************************************************
                                                            FIN - Tabla de Header
                ************************************************************-->
                </td>
            </tr>
            <tr style="width:90%;">
                <td style="width:100%">
                    <!--********************************************************
                                                                Tabla de Body
                    ************************************************************-->
                    <table cellspacing="0" cellpadding="0" style="width:100%; margin:0 auto; background-color: white;">
                        <tr style="width:100%">
                            <td style="max-width:100%; min-width:174px;">
                                <p style="width:96%; margin-left: auto; margin-right: auto; padding-top: 15px;">Saludos,</p>
                                <p style="width:96%; margin: auto;">&nbsp;

                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                    &nbsp;
                                    Este dia cumplimos un a&ntilde;o mas juntos, y por eso felicitamos a quienes con dedicacion y compromiso suman metas alcanzadas en teleSUR.</p></br>
                            </td>
                        </tr>
                        <tr style="width:100%">
                            <td style="max-width:100%; min-width:320px;">
                                <img style="width:100%; min-width:320px;" src="http://localhost/Tarjeta-General-medio.jpg" longdesc="http://localhost/Tarjeta-General-medio.jpg" />
                            </td>
                        </tr>
                        <tr style="width:100%">
                            <td style="max-width:100%; min-width:320px;padding:2px 2px 5px 2px;">
                            </td>
                        </tr>
                        <tr style="width:100%; background-color: #EAEAEA">
                            <td style="max-width:100%; min-width:320px; padding:2px 2px 5px 2px;"></td>
                        </tr>
                        <tr style="width:100%; background-color: #DDD">
                            <td style="max-width:100%; min-width:320px;">
                                <table style="width:100%; margin:0 auto; border: 1px solid #DDD !important;">
