<!DOCTYPE html>
<html lang="es">
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            @import url(//fonts.googleapis.com/css?family=Lato:700);

            body {
                margin:0 auto;
                font-family:'Lato', sans-serif;
                text-align:center;
                color: #373737;
            }
            
            a, a:visited {
                text-decoration:none;
            }

            h1 {
                font-size: 32px;
                margin: 20px 0 10px 0;
            }

            .contenedor {
                margin: 0 auto;
                width: 350px;
                height: 350px;
                background-color: #a2d1f0;
            }
            
            table{
                border-collapse:collapse;
                width: 320px;
                height: 300px;
                position: relative;
                left: 6%;
                text-align: center;
            }

            tr, td, span, strong{
                padding: 0;
                margin-bottom: 10px;
            }

            .fecha{
                font-size: 14px;
                padding: 0;
            }

            .descripcion{
                font-size: 13px;
                padding: 0;
            }
        </style>
    </head>
    <body class="MsgBody MsgBody-html" style="margin: 0px; height: auto;">
        <div class="contenedor">
            <h1>NewsLetter Week</h1>
            <table>
                <thead></thead>
                <tbody>